-optimizationpasses 10
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-optimizations *
-allowaccessmodification
-repackageclasses
-verbose

-dontwarn com.google.re2j.Matcher
-dontwarn com.google.re2j.Pattern
