-optimizationpasses 10
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-optimizations *
-allowaccessmodification
-repackageclasses a
-overloadaggressively
-adaptclassstrings
-adaptresourcefilenames
-adaptresourcefilecontents **
-renamesourcefileattribute x
-ignorewarnings
-dontnote
-verbose

-dontwarn com.google.re2j.Matcher
-dontwarn com.google.re2j.Pattern
